### ISSUE TITLE
Help with question

### ISSUE THREAD

**Issue by ebflhippie** [varingst/awesome-conky#5]
Hello I am sorry if I am bloating your git, but I am new to git commenting. I would like to ask if it is possible to use this tool to toggle displaying a conky window, while keeping it running with both a keybinding and/or clicking the calendar widget in awesome? I use a separate conky config for my calendar, so killall conky apraoches would more than likely cause unwanted effects. Thank you in advance for any help.

**Comment by varingst** [comment]
Hi.

I'm not entirely sure what you mean here. Can you put up your configuration, along with detailing what isn't working, and how you'd like it to work?

By the calendar widget, do you mean the [AwesomeWM calendar widget](https://awesomewm.org/doc/api/classes/awful.widget.calendar_popup.html) or the [gcal widget](https://github.com/varingst/awesome-conky/blob/master/widgets/gcal.lua) ?

If you're asking whether you can use several separate conky processes as backend for conky widgets, that's a no, you can only use one. You may have several other conky processes running for whatever purpose you see fit, but only one to evaluate the conky expressions passed over dbus.

What do you mean by 'killall conky approaches' ? You shouldn't have to kill anything as part of normal operations, no matter what you are doing.

**Comment by ebflhippie** [comment]
I am sorry for the confusion. Firstly, nothing "isn't working" yet. I was attempting to ask if this would be helpful for something I am trying to implement in awesome that will use conky. What I would like to do is create a gcalcli calender with conky that is seperate from my usual conky (this part is already created and works). However I would like to be able to toggle my calender conky on and off (as in upon first use start the particular conky , then hide or show the conky calender) by using awesome keybindings, and or  hovering over my existing calender widget on my wibar. As I am not super familiar with lua and am very new to scripting I may be completely off base asking about this here, if so I am sorry. I have none of this in my config yet, so I will refrain from sending it till I have tried implementing. I really juist wanted to ask if this modual would help me achieve what I am trying to accomplish. I know devs are super busy, so I apologize for taking up you time and thank you very much.

**Comment by varingst** [comment]
Is your calendar rendered by conky itself, on its window?

**Comment by ebflhippie** [comment]
Yes I will paste its config sorry about that. Here is my my conky calender confg. https://pastebin.com/A9PRQghY

**Comment by ebflhippie** [comment]
I don't mind posting my awesome config, but at this point I doubt it would be helpful as I have not added anything concerning this project yet, and it is an awesome copycat config with very little added as of yet.

**Comment by varingst** [comment]
Ah, I see. Conky draws your calendar in its own window there, so you won't need anything here to handle that, you can just use the awesome API.

**Comment by ebflhippie** [comment]
I see thank you for your time.
